import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import dynamic from "next/dynamic";
import { AudioProvider } from "@/components/audio-provider";

const StockfishProvider = dynamic(() =>
    import("@/components/stockfish-provider").then(
        (mod) => mod.StockfishProvider,
    ),
);
const ImagesProvider = dynamic(() =>
    import("@/components/images-provider").then((mod) => mod.ImagesProvider),
);

const ThemeProvider = dynamic(() =>
    import("@/components/theme-provider").then((mod) => mod.ThemeProvider),
);

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AudioProvider>
                    <ImagesProvider>
                        <StockfishProvider>
                            <ThemeProvider
                                attribute="class"
                                defaultTheme="system"
                                enableSystem
                                disableTransitionOnChange
                            >
                                <SidebarProvider>
                                    <AppSidebar />
                                    <SidebarInset>{children}</SidebarInset>
                                </SidebarProvider>
                            </ThemeProvider>
                        </StockfishProvider>
                    </ImagesProvider>
                </AudioProvider>
            </body>
        </html>
    );
}
